# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.17.1"

default_platform :ios

# Build and upload an IPA to Beta by Crashlytics
lane :beta do
  increment_build_number

  # build your iOS app
  gym(
    scheme: "SDKLauncher-iOS",
    configuration: 'Release', #ENV['DEBUG'] ? 'Debug' : 'Release'
    silent: true,
    #clean: true,
    #TODO remove: currently fastlane have trouble with signing
    use_legacy_build_api: true
  )

  # upload to Beta by Crashlytics
  crashlytics(
   crashlytics_path: "/Users/alexandrecamilleri/Desktop/dev/frameworks/Crashlytics-iOS/Crashlytics.framework",
   api_token: "8697fc2d6b052922d0b776297ecd35750f08b5aa",
   build_secret: "97d2dd9b077b4fcfcae94e848193021e9f5d44dd2759b545fb7a525ee0693c2b",
   notes: "New beta build at " + Time.new.strftime("%H:%M:%S %d.%m.%Y")
  )

  #slack(
    # slack_url: "https://hooks.slack.com/services/IDS"
  #)
end
